[package]
name = "tokio_postgres_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] } # latest
tokio-postgres = { version = "0.7.13", features = ["runtime"] }  # latest
# deadpool-postgres = "0.14.1" # latest
dotenv = "0.15.0"
rand = "0.8.4"