[package]
name = "rocksdb_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
rocksdb = "0.23.0"
serde = { version = "1.0.217", features = ["derive"] }
bincode = "1.3.3"
serde_json = "1.0.138"

actix-web = "4"
actix-rt = "2"
sha2 = "0.10.8"
